### PR TITLE
Initial implementation of redirect middleware

### LINKED ISSUE #1: Implement middleware to redirect non-auth routes to login via xpro
Ideally this middleware should be reasonably configurable in case our runtime requirements change

### PR DESCRIPTION
**Pull request by rhysyngsun**
Fixes #1 

Main implementation is at https://github.com/mitodl/mitxpro-openedx-extensions/pull/2/files#diff-57b40ef813f04614ed5f2b6e1c2d5686

### CODE REVIEW

**Comment by gsidebo** [comment]
Can you check to see what happens when you try to logout in LMS when this package is installed and you have done something in mitxpro to redirect to LMS (e.g.: click one of the course links)? In my main browser window I was unable to log out. It looks like the logout redirect is just causing a fresh login. I click "Sign Out" and get redirected to `/logout` where my user is indeed logged out. After the 5 second redirect waiting period, I'm redirected back to `/dashboard` with the same user logged in again. In an incognito window I had a non-mitxpro user logged in. When I clicked "Sign Out" I was eventually redirected here: http://xpro.odl.local:8053/?next=/oauth2/authorize/%3Fscope%3Duser%253Aread%26state%3DkKRGJY9tEzy01Q57UpGLaAJjjxRnRBe0%26redirect_uri%3Dhttp%253A%252F%252Fedx.odl.local%253A18000%252Fauth%252Fcomplete%252Fmitxpro-oauth2%252F%253Fredirect_state%253DkKRGJY9tEzy01Q57UpGLaAJjjxRnRBe0%26response_type%3Dcode%26client_id%3DZyrSE6YWtvWBj20SD5izSWxQhUryyLXBJCLQwusr

We do want to continue to allow users to log out normally on LMS, don't we?

**Comment by rhysyngsun** [comment]
@gsidebo I discussed with @pdpinch and we agreed it's worth getting this out even with that known issue. We may remove the logout button anyway eventually, but I've also logged #3 to deal with this more gracefully

**Comment by gsidebo** [comment]
I guess this would be an edge case in prod, but if I (1) log into xpro, (2) click over to LMS, (3) log out of xpro, (4) log back into xpro with a different user, then (5) click over to LMS again, my first user is still logged into LMS. If this will be solved by #3, please ignore

**Comment by rhysyngsun** [comment]
@gsidebo I think that's a use case that wasn't intended to be covered by this work so we probably need a more comprehensive issue opened up that covers all the auth flows and what would be expected for multi-user situations (assuming we even want to support that).

@pdpinch thoughts on that?

**Comment by gsidebo** [comment]
This seems to be breaking a couple pieces of functionality: new user creation and enrollment. I get this error when I complete registration for a new user (possibly OSX-specific):

```
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
celery_1  |     R = retval = fun(*args, **kwargs)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
celery_1  |     return self.run(*args, **kwargs)
celery_1  |   File "/src/courseware/tasks.py", line 13, in create_edx_user_from_id
celery_1  |     create_edx_auth_token(user)
celery_1  |   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
celery_1  |     return func(*args, **kwds)
celery_1  |   File "/src/courseware/api.py", line 136, in create_edx_auth_token
celery_1  |     f"Redirected to '{resp.url}', expected: '{redirect_uri}'"
celery_1  | courseware.exceptions.OpenEdXOAuth2Error: Redirected to 'http://host.docker.internal:18000/register', expected: 'http://xpro.odl.local:8053/login/_private/complete'
```

When I click the enroll button on a course detail page, that also fails since the first request in `courseware.api._create_tokens_and_update_auth` now returns a different response. Instead of getting a response back with a JSON body, the request seems to be redirected and the response URL is that same xpro URL I mentioned in a previous comment (`http://xpro.odl.local:8053/?next=/oauth2/authorize/%3Fscope%3Duser%253Aread%26state%3DdzK6DOSZJ6nJKcOjK5A3xKPSAFxaLiKB%26redirect_uri%3Dhttp%253A%252F%252Fhost.docker.internal%253A18000%252Fauth%252Fcomplete%252Fmitxpro-oauth2%252F%253Fredirect_state%253DdzK6DOSZJ6nJKcOjK5A3xKPSAFxaLiKB%26response_type%3Dcode%26client_id%3DZyrSE6YWtvWBj20SD5izSWxQhUryyLXBJCLQwusr`).

**Comment by pdpinch** [comment]
I don't think will be solved by #3, so I think we should open another issue to look into it later.

> if I (1) log into xpro, (2) click over to LMS, (3) log out of xpro, (4) log back into xpro with a different user, then (5) click over to LMS again, my first user is still logged into LMS. If this will be solved by #3, please ignore

My initial though would be to log the user out of open edX at the time they log out of xPro. I'm not sure how hard that might be though.

**Comment by rhysyngsun** [comment]
@gsidebo I've fixed the regex to address the API issues

**Review by gsidebo — APPROVED** [review]
Naturally I'm once again getting the issue with full name/country entry when I go over to LMS, but I'm pretty confident that isn't due to this PR. Ship it! 👍

**Pull request merged**
